- hosts: master1
  become: yes
  tasks:
    - name: copy admin.conf to ansible host
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /opt/
- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: copy admin.conf to ansible host
      shell:
              "mv /opt/master/etc/kubernetes/admin.conf ~/.kube/config"
