- hosts: masters
  become: yes
  gather_facts: false
  tasks:
          
    - name: Downloading Helm installation script
      get_url:
        url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
        dest: "/tmp/"
        mode: "0700"

    - name: Installing Helm
      shell: "bash /tmp/get-helm-3"
