- hosts: masters
  become: yes
  become_user: ubuntu
  gather_facts: false
  tasks:
    - name: Add Ingress repository
      shell: "helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx"

    - name: Copying Ingress values file
      copy:
        src: "nginxvalues.yaml"
        dest: "/tmp/nginxvalues.yaml"

    - name: Installing Ingress
      shell: "helm install ingress-nginx -f /tmp/nginxvalues.yaml --namespace ingress-ns --create-namespace ingress-nginx/ingress-nginx"

    - name: Installing Cert-manager helm
      shell: "helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.1.0 --set installCRDs=true"
