- hosts: masters
  become: yes
  gather_facts: false
  tasks:
    - name: Add Ingress repository
      shell: "helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx"

    - name: Add Let's Encrypt repository
      shell: "helm repo add jetstack https://charts.jetstack.io"
    
    - name: Copying Ingress values file
      copy:
        src: "nginxvalues.yaml"
        dest: "/tmp/nginxvalues.yaml"

    - name: Installing Ingress
      shell: "helm install ingress-nginx -f /tmp/nginxvalues.yaml --namespace ingress-ns --create-namespace ingress-nginx/ingress-nginx"

   - name: Installing Cert-manager helm
     shell: "helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.1.0 --set installCRDs=true"

   - name: Copying Cert-manager Values file
     copy:
       src: "issuer.yaml"
       dest: "/tmp/issuer.yaml"

   - name: applying Cert-manager conf
     shell: "kubectl apply --namespace cert-manager -f /tmp/issuer.yaml" 
