ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts users.yml  

echo " INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE "

ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts kube-install.yml -vvvvv 

echo " INSTALLING MASTER  INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER"
ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts masters.yml -vvv

echo " INSTALLING WORKER  INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER"
ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts workers.yml -vvvv

echo " ADDING LINE  ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE ADDING LINE "


ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts sed.yml
