ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts users.yml  

echo " INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE INSTALLING KUBE "

ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts kube-install.yml 

echo " INSTALLING MASTER  INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER INSTALLING MASTER"
ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts masters.yml 

echo " INSTALLING WORKER  INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER INSTALLING WORKER"
ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts workers.yml 

echo " INSTALLING INGRESS AND CERT.IO  INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO INSTALLING INGRESS AND CERT.IO "

ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts ingress-install.yml
