- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  
  tasks:
   - name: Make the Swap inactive
     command: swapoff -a

   - name: Create kernel file for iptables
     file:
        path: "/etc/modules-load.d/k8s.conf"
        state: "touch"

   - name: Add iptables see bridged traffic
     blockinfile:
        path: "/etc/modules-load.d/k8s.conf"
        block: |
              br_netfilter

   - name: Create sysctl file
     file:
        path: "/etc/sysctl.d/k8s.conf"
        state: "touch"

   - name: Add iptables see bridged traffic
     blockinfile:
        path: "/etc/sysctl.d/k8s.conf"
        block: |
              net.bridge.bridge-nf-call-ip6tables = 1
              net.bridge.bridge-nf-call-iptables = 1

   - name: reload sysctl
     shell: |
              sudo sysctl --system

   - name: install and configure dependencies
     shell: |
              sudo apt-get install -y apt-transport-https ca-certificates software-properties-common gnupg2 curl
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key --keyring /etc/apt/trusted.gpg.d/docker.gpg add -
              sudo add-apt-repository --yes "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

   - name: install docker
     shell: |
              sudo apt-get update && sudo apt-get install -y containerd.io=1.2.13-2 docker-ce=5:19.03.11~3-0~ubuntu-$(lsb_release -cs) docker-ce-cli=5:19.03.11~3-0~ubuntu-$(lsb_release -cs)

   - name: Creating a daemon json
     copy:
      dest: "/etc/docker/daemon.json"
      content: |
       {
         "exec-opts": ["native.cgroupdriver=systemd"],
         "log-driver": "json-file",
         "log-opts": {
           "max-size": "100m"
         },
         "storage-driver": "overlay2"
       }

   - name: add Kubernetes apt-key for APT repository
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: add Kubernetes APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'


   - name: install and configure dependencies
     shell: |
       sudo apt-get update
       apt install -y kubelet=1.20.1-00 kubeadm=1.20.1-00 kubectl=1.20.1-00 --allow-downgrades --allow-change-held-packages
       sudo apt-mark hold kubelet kubeadm kubectl

   - name: restarting the docker and kubelet
     shell: |
       systemctl daemon-reload
       systemctl restart docker
       systemctl restart kubelet