- name: Setup Kubernetes Masters
  hosts: masters
  become: true
  tasks:
    - name: Install kubeadm, kubelet, and kubectl
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        update_cache: true

    - name: Initialize Kubernetes cluster on master1
      command: kubeadm init --control-plane-endpoint "master1:6443" --upload-certs
      when: inventory_hostname == "master1"

    - name: Fetch join command for control plane
      shell: kubeadm token create --print-join-command --certificate-key $(kubeadm init phase upload-certs --upload-certs | tail -1)
      run_once: true
      register: join_command

    - name: Join other masters to the control plane
      command: "{{ join_command.stdout }}"
      when: inventory_hostname != "master1"
