- hosts: masters
  become: yes
  tasks:
    - name: Start the cluster
      shell: kubeadm init --control-plane-endpoint cl1.codescalers-egypt.com --upload-certs --pod-network-cidr=10.244.0.0/16 --kubernetes-version=1.20.1 >> cluster.txt
      args:
        chdir: $HOME
        creates: cluster.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
    
    - name: copy admin.conf to ansible host
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /opt/config

    - name: install Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_seltup.txt
      args:
        chdir: $HOME
        creates: pod_setup.txt
