- hosts: masters
  become: true
  gather_facts: false
  tasks:
    - name: Generate kubeadm join command on master1
      shell: kubeadm token create --print-join-command --certificate-key $(kubeadm init phase upload-certs --upload-certs | tail -1)
      register: join_command_raw
      run_once: true

    - name: Set kubeadm join command as a fact
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: true
  gather_facts: false
  tasks:
    - name: Join worker nodes to the cluster
      shell: "{{ hostvars['master1'].join_command }} >> /root/node_joined.txt"
      args:
        chdir: /root
        creates: /root/node_joined.txt

- hosts: masters
  become: true
  gather_facts: false
  tasks:
    - name: Remove NoSchedule taint from master nodes
      shell: kubectl taint nodes --all node-role.kubernetes.io/master- || true
      ignore_errors: true

    - name: Add API server node port range to kube-apiserver
      lineinfile:
        path: "/etc/kubernetes/manifests/kube-apiserver.yaml"
        insertafter: "service-cluster-ip-range"
        line: "    - --service-node-port-range=50-64000"
