- name: Join Kubernetes Workers
  hosts: workers
  become: true
  tasks:
    - name: Install kubeadm, kubelet, and kubectl
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        update_cache: true

    - name: Fetch join command for workers
      shell: kubeadm token create --print-join-command
      delegate_to: master1
      run_once: true
      register: join_command

    - name: Join worker nodes to the cluster
      command: "{{ join_command.stdout }}"

    - name: Remove master node taint to allow workloads
      hosts: masters
      become: true
      tasks:
        - name: Remove taint from master nodes
          shell: kubectl taint nodes --all node-role.kubernetes.io/master-
          ignore_errors: true
